import type { Metadata } from "next";

import { Footer, Header } from "@/widgets/index";
import { Link } from "@/shared/ui/index";

import { iconFinder } from "../../../../public/helpers/index";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DeepLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className=''>
          <Header isArrowBack={true} isBurger={false}></Header>
          <hr className="bg-white h-[1px] pt-[60px]"></hr>
          {children}
          <hr></hr>
        <Footer></Footer>
    </main>
  );
}