import type { Metadata } from "next";

import { Header, Footer } from "@/widgets/index";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
        <Header isArrowBack={false} isBurger={true}></Header>
        {children}
        <Footer></Footer>
    </>
  );
}
